# Generated by Django 5.1.2 on 2024-10-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='etiquetas',
            field=models.CharField(default='sin etiqueta', help_text='Etiquetas separadas por comas, ej: reflexión, conciencia', max_length=200),
        ),
        migrations.AddField(
            model_name='articulo',
            name='tema',
            field=models.CharField(choices=[('FIL', 'Filosofía'), ('PSI', 'Psicología'), ('NEG', 'Negocios')], default='FIL', max_length=3),
        ),
    ]
