# Generated by Django 5.1.2 on 2024-11-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0003_articulo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='contenido',
            field=models.TextField(verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='etiquetas',
            field=models.CharField(default='sin etiqueta', help_text='Etiquetas separadas por comas, ej: reflexión, conciencia', max_length=200, verbose_name='Etiquetas'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicación'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_articulos/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='tema',
            field=models.CharField(choices=[('FIL', 'Filosofía'), ('PSI', 'Psicología'), ('NEG', 'Negocios')], default='FIL', max_length=3, verbose_name='Tema'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]
