# Generated by Django 5.1.2 on 2024-11-20 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0004_alter_articulo_contenido_alter_articulo_etiquetas_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulo',
            options={'ordering': ['-fecha_publicacion'], 'verbose_name': 'Artículo', 'verbose_name_plural': 'Artículos'},
        ),
        migrations.AlterField(
            model_name='articulo',
            name='etiquetas',
            field=models.CharField(blank=True, help_text='Etiquetas separadas por comas, ej: reflexión, conciencia', max_length=200, null=True, verbose_name='Etiquetas'),
        ),
    ]
